// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240814121148_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Disponibilite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LogementId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogementId");

                    b.ToTable("Disponibilites");
                });

            modelBuilder.Entity("Logement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresseComplete")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Chambres")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionLongue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Galerie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrixParAdulte")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrixParEnfant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProprietaireId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Voyageurs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProprietaireId");

                    b.ToTable("Logements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdresseComplete = "123 Rue de Paris, 75001 Paris, France",
                            Chambres = 2,
                            Description = "Charmant loft au cœur de Paris, à proximité de la Tour Eiffel.",
                            DescriptionLongue = "Magnifique loft situé au cœur de Paris, à deux pas de la Tour Eiffel. Ce lieu unique allie charme parisien et design contemporain avec ses grandes baies vitrées qui inondent l'espace de lumière, ses poutres apparentes, et son parquet en bois massif. La pièce à vivre spacieuse et ouverte inclut une cuisine américaine moderne, parfaite pour recevoir ou savourer des repas tranquilles. La chambre en mezzanine offre une vue imprenable sur les toits de Paris, tandis que la salle de bain élégante invite à la détente. À proximité immédiate des cafés, restaurants, boutiques et galeries, ce loft est une véritable perle rare pour vivre pleinement l’expérience parisienne.",
                            Galerie = "[\"ny.jpg\",\"tokyo.png\",\"paris.jpg\"]",
                            ImageName = "paris.jpg",
                            Options = "[\"Ville\",\"Mus\\u00E9es\",\"Restaurants\",\"Stations de m\\u00E9tro\",\"Appartement\",\"Wi-Fi\",\"Climatisation\",\"Cuisine \\u00E9quip\\u00E9e\",\"Balcon/Terrasse\",\"Acc\\u00E8s aux personnes handicap\\u00E9es\",\"S\\u00E9jour longue dur\\u00E9e\",\"S\\u00E9jour romantique\",\"Petit-d\\u00E9jeuner inclus\",\"Service de m\\u00E9nage\",\"Luxe\",\"Moderne\",\"Politique d\\u0027annulation\"]",
                            Pays = "France",
                            PrixParAdulte = 120m,
                            PrixParEnfant = 60m,
                            ProprietaireId = 1,
                            Rating = 4.7000000000000002,
                            Ville = "Paris",
                            Voyageurs = 4
                        },
                        new
                        {
                            Id = 2,
                            AdresseComplete = "456 Rue de Londres, SW1A 1AA Londres, Royaume-Uni",
                            Chambres = 3,
                            Description = "Appartement moderne à Londres, proche de la Tamise.",
                            DescriptionLongue = "Appartement moderne situé à Londres, à proximité de la Tamise. Ce lieu unique allie charme londonien et design contemporain avec ses grandes baies vitrées qui inondent l'espace de lumière, ses poutres apparentes, et son parquet en bois massif. La pièce à vivre spacieuse et ouverte inclut une cuisine américaine moderne, parfaite pour recevoir ou savourer des repas tranquilles. La chambre en mezzanine offre une vue imprenable sur les toits de Londres, tandis que la salle de bain élégante invite à la détente. À proximité immédiate des cafés, restaurants, boutiques et galeries, cet appartement est une véritable perle rare pour vivre pleinement l’expérience londonienne.",
                            Galerie = "[\"london1.jpg\",\"london2.png\",\"london3.jpg\"]",
                            ImageName = "london.jpg",
                            Options = "[\"Ville\",\"Mus\\u00E9es\",\"Restaurants\",\"Stations de m\\u00E9tro\",\"Appartement\",\"Wi-Fi\",\"Climatisation\",\"Cuisine \\u00E9quip\\u00E9e\",\"Balcon/Terrasse\",\"Acc\\u00E8s aux personnes handicap\\u00E9es\",\"S\\u00E9jour longue dur\\u00E9e\",\"S\\u00E9jour romantique\",\"Petit-d\\u00E9jeuner inclus\",\"Service de m\\u00E9nage\",\"Luxe\",\"Moderne\",\"Politique d\\u0027annulation\"]",
                            Pays = "Royaume-Uni",
                            PrixParAdulte = 150m,
                            PrixParEnfant = 75m,
                            ProprietaireId = 1,
                            Rating = 4.7999999999999998,
                            Ville = "Londres",
                            Voyageurs = 5
                        },
                        new
                        {
                            Id = 3,
                            AdresseComplete = "789 Rue de New York, NY 10001 New York, États-Unis",
                            Chambres = 4,
                            Description = "Penthouse luxueux à New York, vue sur Central Park.",
                            DescriptionLongue = "Penthouse luxueux situé à New York, avec vue sur Central Park. Ce lieu unique allie charme new-yorkais et design contemporain avec ses grandes baies vitrées qui inondent l'espace de lumière, ses poutres apparentes, et son parquet en bois massif. La pièce à vivre spacieuse et ouverte inclut une cuisine américaine moderne, parfaite pour recevoir ou savourer des repas tranquilles. La chambre en mezzanine offre une vue imprenable sur les toits de New York, tandis que la salle de bain élégante invite à la détente. À proximité immédiate des cafés, restaurants, boutiques et galeries, ce penthouse est une véritable perle rare pour vivre pleinement l’expérience new-yorkaise.",
                            Galerie = "[\"ny1.jpg\",\"ny2.png\",\"ny3.jpg\"]",
                            ImageName = "newyork.jpg",
                            Options = "[\"Ville\",\"Mus\\u00E9es\",\"Restaurants\",\"Stations de m\\u00E9tro\",\"Appartement\",\"Wi-Fi\",\"Climatisation\",\"Cuisine \\u00E9quip\\u00E9e\",\"Balcon/Terrasse\",\"Acc\\u00E8s aux personnes handicap\\u00E9es\",\"S\\u00E9jour longue dur\\u00E9e\",\"S\\u00E9jour romantique\",\"Petit-d\\u00E9jeuner inclus\",\"Service de m\\u00E9nage\",\"Luxe\",\"Moderne\",\"Politique d\\u0027annulation\"]",
                            Pays = "États-Unis",
                            PrixParAdulte = 200m,
                            PrixParEnfant = 100m,
                            ProprietaireId = 1,
                            Rating = 4.9000000000000004,
                            Ville = "New York",
                            Voyageurs = 6
                        },
                        new
                        {
                            Id = 4,
                            AdresseComplete = "123 Rue de Tokyo, 150-0001 Tokyo, Japon",
                            Chambres = 2,
                            Description = "Appartement traditionnel à Tokyo, proche du quartier Shibuya.",
                            DescriptionLongue = "Appartement traditionnel situé à Tokyo, à proximité du quartier Shibuya. Ce lieu unique allie charme tokyoïte et design contemporain avec ses grandes baies vitrées qui inondent l'espace de lumière, ses poutres apparentes, et son parquet en bois massif. La pièce à vivre spacieuse et ouverte inclut une cuisine américaine moderne, parfaite pour recevoir ou savourer des repas tranquilles. La chambre en mezzanine offre une vue imprenable sur les toits de Tokyo, tandis que la salle de bain élégante invite à la détente. À proximité immédiate des cafés, restaurants, boutiques et galeries, cet appartement est une véritable perle rare pour vivre pleinement l’expérience tokyoïte.",
                            Galerie = "[\"tokyo1.jpg\",\"tokyo2.png\",\"tokyo3.jpg\"]",
                            ImageName = "tokyo.jpg",
                            Options = "[\"Ville\",\"Mus\\u00E9es\",\"Restaurants\",\"Stations de m\\u00E9tro\",\"Appartement\",\"Wi-Fi\",\"Climatisation\",\"Cuisine \\u00E9quip\\u00E9e\",\"Balcon/Terrasse\",\"Acc\\u00E8s aux personnes handicap\\u00E9es\",\"S\\u00E9jour longue dur\\u00E9e\",\"S\\u00E9jour romantique\",\"Petit-d\\u00E9jeuner inclus\",\"Service de m\\u00E9nage\",\"Luxe\",\"Moderne\",\"Politique d\\u0027annulation\"]",
                            Pays = "Japon",
                            PrixParAdulte = 180m,
                            PrixParEnfant = 90m,
                            ProprietaireId = 1,
                            Rating = 4.5999999999999996,
                            Ville = "Tokyo",
                            Voyageurs = 4
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Digicode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Filterhistory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("LogementId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogementId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1999, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Digicode = "0000",
                            Email = "admin@example.com",
                            Filterhistory = "[]",
                            Firstname = "adem",
                            Lastname = "Een",
                            Password = "$2a$10$BaXgWcAEv6NTNeuWZyPz2.IApa3YHX9zgh3OyD50dbN/DxMBQpQce",
                            Phonenumber = "+32492201522",
                            Picture = "",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Disponibilite", b =>
                {
                    b.HasOne("Logement", "Logement")
                        .WithMany("Disponibilites")
                        .HasForeignKey("LogementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logement");
                });

            modelBuilder.Entity("Logement", b =>
                {
                    b.HasOne("User", "Proprietaire")
                        .WithMany()
                        .HasForeignKey("ProprietaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proprietaire");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Logement", null)
                        .WithMany("Visiteurs")
                        .HasForeignKey("LogementId");
                });

            modelBuilder.Entity("Logement", b =>
                {
                    b.Navigation("Disponibilites");

                    b.Navigation("Visiteurs");
                });
#pragma warning restore 612, 618
        }
    }
}
